package_bundle_and_publish:
  image: graviteeio/python3
  environment:
    - BINTRAY_BASIC_TOKEN
    - RELEASE_VERSION
    - PUBLISH_TO_BINTRAY
  volumes:
    - ./../../../:/usr/src/myapp
  working_dir: /usr/src/myapp
  command: ["python", "./src/main/python/package_bundles.py"]
